### ISSUE TITLE
Sell and buy orders fail after one fails

### ISSUE THREAD

**Issue by bor0ka** [bitshares/python-bitshares#102]
from bitshares import BitShares
from bitshares.account import Account
from bitshares.asset import Asset
from bitshares.market import Market
from bitshares.amount import Amount
from bitshares.dex import Dex
from bitshares.price import Price

bitshares = BitShares(node="wss://bitshares.openledger.info/ws", keys='xxxx')
my_account = 'xxxxxx' 
market = Market('BTS:USD')

```
>>>sell = market.sell(0.23, 0.1, account=my_account,  killfill=True)

Traceback (most recent call last):
** IDLE Internal Exception: 
  File "/usr/local/lib/python3.5/dist-packages/bitsharesapi/bitsharesnoderpc.py", line 54, in rpcexec
    return self.rpc.rpcexec(self, payload)
  File "/usr/local/lib/python3.5/dist-packages/grapheneapi/graphenewsrpc.py", line 173, in rpcexec
    raise RPCError(ret['error']['message'])
grapheneapi.exceptions.RPCError: Assert Exception: !op.fill_or_kill || filled: 

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<pyshell#13>", line 1, in <module>
    sell = market.sell(0.23, 0.1, account=my_account, killfill=True)
  File "/usr/local/lib/python3.5/dist-packages/bitshares/market.py", line 515, in sell
    tx = self.blockchain.finalizeOp(order, account["name"], "active", **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/bitshares/bitshares.py", line 293, in finalizeOp
    return self.txbuffer.broadcast()
  File "/usr/local/lib/python3.5/dist-packages/bitshares/transactionbuilder.py", line 387, in broadcast
    raise e
  File "/usr/local/lib/python3.5/dist-packages/bitshares/transactionbuilder.py", line 385, in broadcast
    ret, api="network_broadcast")
bitsharesapi.exceptions.UnhandledRPCError: Assert Exception: !op.fill_or_kill || filled:
```

And after that does not work` market.sell(), market.buy(), market.cancel()`.

```
>>> sell = market.sell(0.23, 0.1, account=my_account)

Traceback (most recent call last):
** IDLE Internal Exception: 
  File "/usr/local/lib/python3.5/dist-packages/bitsharesapi/bitsharesnoderpc.py", line 54, in rpcexec
    return self.rpc.rpcexec(self, payload)
  File "/usr/local/lib/python3.5/dist-packages/grapheneapi/graphenewsrpc.py", line 173, in rpcexec
    raise RPCError(ret['error']['message'])
grapheneapi.exceptions.RPCError: Assert Exception: !op.fill_or_kill || filled: 

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<pyshell#14>", line 1, in <module>
    sell = market.sell(0.23, 0.1, account=my_account)
  File "/usr/local/lib/python3.5/dist-packages/bitshares/market.py", line 515, in sell
    tx = self.blockchain.finalizeOp(order, account["name"], "active", **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/bitshares/bitshares.py", line 293, in finalizeOp
    return self.txbuffer.broadcast()
  File "/usr/local/lib/python3.5/dist-packages/bitshares/transactionbuilder.py", line 387, in broadcast
    raise e
  File "/usr/local/lib/python3.5/dist-packages/bitshares/transactionbuilder.py", line 385, in broadcast
    ret, api="network_broadcast")
bitsharesapi.exceptions.UnhandledRPCError: Assert Exception: !op.fill_or_kill || filled:
```

**Comment by xeroc** [comment]
should be fixed with
https://github.com/bitshares/python-bitshares/commit/f0ca80d3b71a8c9614b3c29569cf7a4f8baab8e0
