### ISSUE TITLE
KeyError: 'symbol'

### ISSUE THREAD

**Issue by songxiaoxiao** [bitshares/python-bitshares#127]
Traceback (most recent call last):
  File "webservice.py", line 147, in getbalances_mt
    result_data = wallet.get_balances(data)
  File "./com/morningtech/bts/adapter/wallet.py", line 198, in get_balances
    logger.info(acc_int.balances)
  File "/usr/lib/python3.4/site-packages/bitshares/account.py", line 94, in balances
    for b in balances if int(b["amount"]) > 0
  File "/usr/lib/python3.4/site-packages/bitshares/account.py", line 94, in <listcomp>
    for b in balances if int(b["amount"]) > 0
  File "/usr/lib/python3.4/site-packages/bitshares/amount.py", line 76, in __init__
    self["symbol"] = self["asset"]["symbol"]
  File "/usr/lib/python3.4/site-packages/bitshares/blockchainobject.py", line 162, in __getitem__
    return super().__getitem__(key)
KeyError: 'symbol'
e: 'symbol'
{'code': '400', 'data': '', 'msg': "'symbol'"}

This error occurs when the interface is called many times. What is the reason?

**Comment by songxiaoxiao** [comment]
![image](https://user-images.githubusercontent.com/11972980/43936454-1d751654-9c8b-11e8-8bc7-8380426c04ac.png)

**Comment by xeroc** [comment]
`account.balances` is a property that contains a **list** of instances of **Amount**.

Hence, you'd need to do
```
b = account.balances
b[0]["asset"]["symbol"]
```
