### ISSUE TITLE
account refresh() "KeyError: 0"

### ISSUE THREAD

**Issue by bitphage** [bitshares/python-bitshares#129]
Example traceback:

```
Traceback (most recent call last):
  File "dexbot\worker.py", line 122, in on_block
  File "lib\site-packages\events-0.3-py3.5.egg\events\events.py", line 95, in __call__
  File "dexbot\strategies\staggered_sell.py", line 132, in on_market_update_wrapper
  File "dexbot\strategies\staggered_sell.py", line 222, in check_orders
  File "dexbot\strategies\staggered_sell.py", line 292, in update_orders
  File "dexbot\basestrategy.py", line 568, in total_balance
  File "dexbot\basestrategy.py", line 590, in orders_balance
  File "dexbot\basestrategy.py", line 303, in get_updated_order
  File "dexbot\basestrategy.py", line 314, in updated_open_orders
  File "lib\site-packages\bitshares-0.1.19-py3.5.egg\bitshares\account.py", line 61, in refresh
KeyError: 0
```

Code executed:
```python
account.refresh()
```

Library code where error happened:

```python
            account = self.blockchain.rpc.get_full_accounts(
                [account["id"]], False)[0][1]
```

The error probably caused by bad node connectivity or answer. Maybe we need to add some error handling or raise a more meaningful exception.

**Comment by xeroc** [comment]
I agree .. after the querty, it should be ensured that the response is a list else through AccountNotExists exception
