### ISSUE TITLE
transactionbuilder.py AttributeError: 'list' object has no attribute 'update'

### ISSUE THREAD

**Issue by bitfag** [bitshares/python-bitshares#130]
Example traceback:

```
Traceback (most recent call last):
  File "dexbot\worker.py", line 122, in on_block
  File "lib\site-packages\events-0.3-py3.5.egg\events\events.py", line 95, in __call__
  File "dexbot\strategies\staggered_sell.py", line 132, in on_market_update_wrapper
  File "dexbot\strategies\staggered_sell.py", line 222, in check_orders
  File "dexbot\strategies\staggered_sell.py", line 434, in update_orders
  File "dexbot\basestrategy.py", line 509, in market_sell
  File "dexbot\basestrategy.py", line 614, in retry_action
  File "lib\site-packages\bitshares-0.1.19-py3.5.egg\bitshares\market.py", line 510, in sell
  File "lib\site-packages\bitshares-0.1.19-py3.5.egg\bitshares\bitshares.py", line 275, in finalizeOp
  File "lib\site-packages\bitshares-0.1.19-py3.5.egg\bitshares\transactionbuilder.py", line 398, in broadcast
  File "lib\site-packages\bitshares-0.1.19-py3.5.egg\bitshares\transactionbuilder.py", line 393, in broadcast
AttributeError: 'list' object has no attribute 'update'
```

Library code:
```python
ret.update(**ret.get("trx"))
```

Probably need to add handling for bad API response or so.

**Comment by xeroc** [comment]
I suppose this can be closed
