### ISSUE TITLE
price.py return ValueError: could not convert string to float: 

### ISSUE THREAD

**Issue by joelvai** [bitshares/python-bitshares#187]
> ...
  File "/home/joel/projects/DEXBot/dexbot/strategies/base.py", line 680, in get_market_buy_price
    highest_bid = self.ticker().get('highestBid')
  File "/home/joel/projects/DEXBot/venv/lib/python3.6/site-packages/bitshares-0.2.1-py3.6.egg/bitshares/market.py", line 160, in ticker
    blockchain_instance=self.blockchain
  File "/home/joel/projects/DEXBot/venv/lib/python3.6/site-packages/bitshares-0.2.1-py3.6.egg/bitshares/price.py", line 117, in __init__
    frac = Fraction(float(price)).limit_denominator(10 ** base["precision"])
ValueError: could not convert string to float:

Following error occurs when trying to get `highestBid` from an empty market.

Dependencies in use
- bitshares 0.3.0
- graphenelib 1.1.11

**Comment by xeroc** [comment]
Your log shows that you use `bitshares-0.2.1-py3.6.egg` not bitshares-0.3.0

**Comment by joelvai** [comment]
Yeah, well that might have something do with it. I will test once more, thanks for pointing out. /facepalm

**Comment by joelvai** [comment]
I tried to run again, this time making sure it was using 0.3.0. Would this be more helpful?

> Traceback (most recent call last):
  File "/home/joel/projects/DEXBot/dexbot/worker.py", line 76, in init_workers
    view=self.view
  File "/home/joel/projects/DEXBot/dexbot/strategies/relative_orders.py", line 86, in __init__
    self.market_center_price = self.get_market_center_price(suppress_errors=True)
  File "/home/joel/projects/DEXBot/dexbot/strategies/base.py", line 635, in get_market_center_price
    base_amount=base_amount, exclude_own_orders=False)
  File "/home/joel/projects/DEXBot/dexbot/strategies/base.py", line 680, in get_market_buy_price
    test = self.ticker().get('highestBid')
  File "/home/joel/projects/DEXBot/venv-2/lib/python3.6/site-packages/bitshares/market.py", line 161, in ticker
    blockchain_instance=self.blockchain,
  File "/home/joel/projects/DEXBot/venv-2/lib/python3.6/site-packages/graphenecommon/instance.py", line 35, in __init__
    cls.__init__(self, *args, **kwargs)
  File "/home/joel/projects/DEXBot/venv-2/lib/python3.6/site-packages/graphenecommon/price.py", line 146, in __init__
    frac = Fraction(float(price)).limit_denominator(10 ** base["precision"])
ValueError: could not convert string to float:

**Comment by joelvai** [comment]
Has there been any update to this?

**Comment by xeroc** [comment]
I hope the fix above resolves the issue.
