### ISSUE TITLE
Sign tx in TEST network

### ISSUE THREAD

**Issue by lilcryptopump** [bitshares/python-bitshares#260]
I try to sign a transaction, but I get an error

```python
import struct
from binascii import hexlify, unhexlify

from bitshares import BitShares
from bitshares.blockchain import Blockchain
from bitsharesbase.signedtransactions import Signed_Transaction
from bitsharesbase import transactions, memo, account, operations, objects

from graphenebase.transactions import formatTimeFromNow

blockchain = Blockchain(
	bitshares_instance = BitShares(
	"wss://node.testnet.bitshares.eu",
	nobroadcast=False,
	bundle=False,
	)
)

wifs = ["***"]

op = operations.Transfer(**{
	"fee": objects.Asset(amount=100, asset_id="1.3.0"),
	"from": "1.2.24152",
	"to": "1.2.24141",
	"amount": 100,
	"prefix": "TEST",
	}
)

ops = []
ops.append(objects.Operation(op))
info = blockchain.info()

tx = Signed_Transaction(
	ref_block_num = info["head_block_number"],
	ref_block_prefix = struct.unpack_from("<I", unhexlify(info["head_block_id"]), 4)[0],
	expiration = formatTimeFromNow(30),
	operations=ops,
)

w = tx.sign(wifs, chain="TEST")
print(w)
```

```
Traceback (most recent call last):
  File "transfer_back_to_issuer.py", line 105, in <module>
    w = tx.sign(wifs, chain="TEST")
  File "/home/linux_username/.local/lib/python3.7/site-packages/graphenebase/signedtransactions.py", line 188, in sign
    self.deriveDigest(chain)
  File "/home/linux_username/.local/lib/python3.7/site-packages/graphenebase/signedtransactions.py", line 148, in deriveDigest
    self.message = unhexlify(self.chainid) + bytes(self)
  File "/home/linux_username/.local/lib/python3.7/site-packages/graphenebase/objects.py", line 201, in __bytes__
    b += bytes(value)
  File "/home/linux_username/.local/lib/python3.7/site-packages/graphenebase/types.py", line 76, in __bytes__
    return struct.pack("<H", self.data)
struct.error: ushort format requires 0 <= number <= (0x7fff * 2 + 1)

```

The error disappears if `ref_block_num` is reduced, but how to sign a transaction with the current number of blocks?

**Comment by lilcryptopump** [comment]
```
bitshares==0.4.0
graphenelib==1.1.20
```

Python 3.7.0

**Comment by lilcryptopump** [comment]
Worked with `bitshares.finalizeOp`. 
Sorry for issues

**Comment by qualwebs** [comment]
> Worked with `bitshares.finalizeOp`. Sorry for issues

Hi @lilcryptopump 
What you did? I'm facing the same issue.

How to sign transaction using finalizeOp on TESTNET?
