### ISSUE TITLE
Memo encryption doesn't work - shows ** on Bitshares and manual decryption throws error

### ISSUE THREAD

**Issue by darklow** [bitshares/python-bitshares#50]
I made a transfer using following code in python 3.6.4 / bitshares==0.1.11:
```py
from bitshares import BitShares
bitshares = BitShares(keys={pub_key: priv_key})
bitshares.transfer('abc', 0.01, 'ABC', 'test-memo', 'def')
```
And it shows two asterisks as memo on BitShares dex no matter what I write as memo text:
![image](https://user-images.githubusercontent.com/445304/36941707-e638a8d2-1f61-11e8-907b-f564abe14ff8.png)

When I try manually encrypting and decrypting memo, I got an error while decrypting:
```py
from bitshares import BitShares
from bitshares.memo import Memo

bitshares = BitShares(keys={pub_key: priv_key})

memoObj = Memo(
    from_account=from_account,
    to_account=to_account,
    bitshares_instance=bitshares
)
enc = memoObj.encrypt('test')
memoObj.decrypt(enc)
```

Error:
```
Traceback (most recent call last):
  File "/Users/darklow/www/abc/env/lib/python3.6/site-packages/bitsharesbase/memo.py", line 116, in decode_memo
    return _unpad(message.decode('utf8'), 16)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xd5 in position 4: invalid continuation byte

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "./manage.py", line 15, in <module>
    execute_from_command_line(sys.argv)
  File "/Users/darklow/www/abc/env/lib/python3.6/site-packages/django/core/management/__init__.py", line 371, in execute_from_command_line
    utility.execute()
  File "/Users/darklow/www/abc/env/lib/python3.6/site-packages/django/core/management/__init__.py", line 365, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/Users/darklow/www/abc/env/lib/python3.6/site-packages/django/core/management/base.py", line 288, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/Users/darklow/www/abc/env/lib/python3.6/site-packages/django/core/management/base.py", line 335, in execute
    output = self.handle(*args, **options)
  File "/Users/darklow/www/abc/abc-swap/abcswap/management/commands/send_to_bitshares.py", line 13, in handle
    bitshares_sender.test(options['pub_key'], options['priv_key'])
  File "/Users/darklow/www/abc/abc-swap/abcswap/lib/bitshares_sender.py", line 36, in test
    memoObj.decrypt(enc)
  File "/Users/darklow/www/abc/env/lib/python3.6/site-packages/bitshares/memo.py", line 133, in decrypt
    memo.get("message")
  File "/Users/darklow/www/abc/env/lib/python3.6/site-packages/bitsharesbase/memo.py", line 118, in decode_memo
    raise ValueError(message)
ValueError: b'i\x1bf8\xd5A\xd2^X\xaf\xe0v'
```

**Comment by xeroc** [comment]
This may well be an issue with the accounts.
If they have a memo key that is different from the active key, then you need to add both, the memo and the active key to your `BitShares()` instance.
Note that you can use `BitShares(keys=[wif1, wif2, wi3...])` and don't need to provide pubkey (the lib should know what to do and when to use which one).
Also note that the library can technically encode anything using any key and does not check if the webwallet will be able to decode it.

Can you tell us which account names you are working with?
