### ISSUE TITLE
python-bitshares websocket doesn't handle well failing ssl handshakes

### ISSUE THREAD

**Issue by mikakoi** [bitshares/python-bitshares#58]
For example node wss://eu.nodes.bitshares.works fails ssl handshake and the websocket keeps trying to connect to the node. 
I think the connection should simply be killed and error raised in case of a ssl handshake failure.
Here's the traceback:
```
[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:645)
Traceback (most recent call last):
  File "/home/mika/scripts/DEXBot/venv/lib/python3.5/site-packages/websocket_client-0.47.0-py3.5.egg/websocket/_app.py", line 234, in run_forever
    host=host, origin=origin)
  File "/home/mika/scripts/DEXBot/venv/lib/python3.5/site-packages/websocket_client-0.47.0-py3.5.egg/websocket/_core.py", line 217, in connect
    options.pop('socket', None))
  File "/home/mika/scripts/DEXBot/venv/lib/python3.5/site-packages/websocket_client-0.47.0-py3.5.egg/websocket/_http.py", line 76, in connect
    sock = _ssl_socket(sock, options.sslopt, hostname)
  File "/home/mika/scripts/DEXBot/venv/lib/python3.5/site-packages/websocket_client-0.47.0-py3.5.egg/websocket/_http.py", line 191, in _ssl_socket
    sock = _wrap_sni_socket(sock, sslopt, hostname, check_hostname)
  File "/home/mika/scripts/DEXBot/venv/lib/python3.5/site-packages/websocket_client-0.47.0-py3.5.egg/websocket/_http.py", line 168, in _wrap_sni_socket
    server_hostname=hostname,
  File "/usr/lib/python3.5/ssl.py", line 377, in wrap_socket
    _context=self)
  File "/usr/lib/python3.5/ssl.py", line 752, in __init__
    self.do_handshake()
  File "/usr/lib/python3.5/ssl.py", line 988, in do_handshake
    self._sslobj.do_handshake()
  File "/usr/lib/python3.5/ssl.py", line 633, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:645)
```

**Comment by xeroc** [comment]
This was a backend problem with the SSL certs.
Please try again.

**Comment by mikakoi** [comment]
Shouldn't the error still be caught in the websocket? It might have been a temporal issue but it still should be addressed in case it happens again in the future.

**Comment by wshaman** [comment]
is my issue related to this one?
`[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:777)
[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:777)
Lost connection to node during rpcexec(): wss://node.bitshares.eu (2/-1) Retrying in 2 seconds
[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:777)
Lost connection to node during rpcexec(): wss://node.bitshares.eu (3/-1) Retrying in 4 seconds`
..etc
Now I'm forced to use bitshares==0.1.8 cuz any later release, up to 0.1.13 fails for me.

**Comment by kohako** [comment]
Hi I get this issue as well trying to load up for the first time. Mac version. 
[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:833)
[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:833)
Lost connection to node during rpcexec(): wss://bitshares.openledger.info/ws (2/-1) Retrying in 2 seconds
[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:833)
Lost connection to node during rpcexec(): wss://bitshares.openledger.info/ws (3/-1) Retrying in 4 seconds
[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:833)
Lost connection to node during rpcexec(): wss://bitshares.openledger.info/ws (4/-1) Retrying in 6 seconds

**Comment by xeroc** [comment]
I believe this has been fixed by more relaxed SSL handshake parameters on the loadbalnacer
