### ISSUE TITLE
Committee query error

### ISSUE THREAD

**Issue by grctest** [bitshares/python-bitshares#69]
```
Traceback (most recent call last):
  File "a.py", line 36, in <module>
    test = Committee("1.5.10", False)
  File "/home/user/python-bitshares/bitshares/blockchainobject.py", line 101, in __init__
    self.refresh()
  File "/home/user/python-bitshares/bitshares/committee.py", line 40, in refresh
    self.account_id = account["id"]
UnboundLocalError: local variable 'account' referenced before assignment
```

Am I using the committee function incorrectly?

I was just testing it out:

```
test = Committee("1.5.10", False)

print(test)

for a in test:
  print(a)

```

**Comment by jhtitor** [comment]
Nice catch. Here's the fix: #80
