### ISSUE TITLE
All sell and buy orders fail after one fails if no new bitshares instance is created

### ISSUE THREAD

**Issue by TuJuXorX** [bitshares/python-bitshares#86]
I'm trying to trade two CryptoBridge coins using the following code:

```python
from bitshares import BitShares
from bitshares.market import Market

symbol1 = 'BRIDGE.ALQO'
symbol2 = 'BRIDGE.ROE'

account_name = 'xxxxxxxx'
password = 'xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx' 

bitshares = BitShares()

try:
    market1 = Market(symbol1 + ':BRIDGE.BTC', bitshares_instance=bitshares)
    market1.bitshares.wallet.unlock(password)
    market1.sell(price=0.00003302, amount=10, account=account_name)
except:
    print('This fails.')

market2 = Market(symbol2 + ':BRIDGE.BTC', bitshares_instance=bitshares)
market2.bitshares.wallet.unlock(password)
market2.sell(price=0.00001685, amount=10, account=account_name)
```

Trading of BRIDGE.ALQO is currently disable, so Python returns an error (as it should) without try-except:
```
/root/.local/lib/python3.5/site-packages/graphenelib-0.6.1-py3.5.egg/graphenebase/ecdsa.py:187: CryptographyDeprecationWarning: signer and verifier have been deprecated. Please use sign and verify instead.
Traceback (most recent call last):
  File "/root/.local/lib/python3.5/site-packages/bitshares-0.1.13-py3.5.egg/bitsharesapi/bitsharesnoderpc.py", line 54, in rpcexec
  File "/root/.local/lib/python3.5/site-packages/graphenelib-0.6.1-py3.5.egg/grapheneapi/graphenewsrpc.py", line 173, in rpcexec
grapheneapi.exceptions.RPCError: Assert Exception: _sell_asset->options.whitelist_markets.find(_receive_asset->id) != _sell_asset->options.whitelist_markets.end(): 

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "test3.py", line 18, in <module>
    market1.sell(price=0.00003302, amount=100, account=account_name)
  File "/root/.local/lib/python3.5/site-packages/bitshares-0.1.13-py3.5.egg/bitshares/market.py", line 513, in sell
  File "/root/.local/lib/python3.5/site-packages/bitshares-0.1.13-py3.5.egg/bitshares/bitshares.py", line 293, in finalizeOp
  File "/root/.local/lib/python3.5/site-packages/bitshares-0.1.13-py3.5.egg/bitshares/transactionbuilder.py", line 388, in broadcast
  File "/root/.local/lib/python3.5/site-packages/bitshares-0.1.13-py3.5.egg/bitshares/transactionbuilder.py", line 386, in broadcast
  File "/root/.local/lib/python3.5/site-packages/graphenelib-0.6.1-py3.5.egg/grapheneapi/graphenewsrpc.py", line 213, in method
  File "/root/.local/lib/python3.5/site-packages/bitshares-0.1.13-py3.5.egg/bitsharesapi/bitsharesnoderpc.py", line 64, in rpcexec
bitsharesapi.exceptions.UnhandledRPCError: Assert Exception: _sell_asset->options.whitelist_markets.find(_receive_asset->id) != _sell_asset->options.whitelist_markets.end():
```
WITH the try-except I would have except the latter sell order to go through. However, it instead seems to produce the same errors:
```
/root/.local/lib/python3.5/site-packages/graphenelib-0.6.1-py3.5.egg/graphenebase/ecdsa.py:187: CryptographyDeprecationWarning: signer and verifier have been deprecated. Please use sign and verify instead.
This fails.
Traceback (most recent call last):
  File "/root/.local/lib/python3.5/site-packages/bitshares-0.1.13-py3.5.egg/bitsharesapi/bitsharesnoderpc.py", line 54, in rpcexec
  File "/root/.local/lib/python3.5/site-packages/graphenelib-0.6.1-py3.5.egg/grapheneapi/graphenewsrpc.py", line 173, in rpcexec
grapheneapi.exceptions.RPCError: Assert Exception: _sell_asset->options.whitelist_markets.find(_receive_asset->id) != _sell_asset->options.whitelist_markets.end(): 

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "test3.py", line 24, in <module>
    market2.sell(price=0.00001685, amount=100, account=account_name)
  File "/root/.local/lib/python3.5/site-packages/bitshares-0.1.13-py3.5.egg/bitshares/market.py", line 513, in sell
  File "/root/.local/lib/python3.5/site-packages/bitshares-0.1.13-py3.5.egg/bitshares/bitshares.py", line 293, in finalizeOp
  File "/root/.local/lib/python3.5/site-packages/bitshares-0.1.13-py3.5.egg/bitshares/transactionbuilder.py", line 388, in broadcast
  File "/root/.local/lib/python3.5/site-packages/bitshares-0.1.13-py3.5.egg/bitshares/transactionbuilder.py", line 386, in broadcast
  File "/root/.local/lib/python3.5/site-packages/graphenelib-0.6.1-py3.5.egg/grapheneapi/graphenewsrpc.py", line 213, in method
  File "/root/.local/lib/python3.5/site-packages/bitshares-0.1.13-py3.5.egg/bitsharesapi/bitsharesnoderpc.py", line 64, in rpcexec
bitsharesapi.exceptions.UnhandledRPCError: Assert Exception: _sell_asset->options.whitelist_markets.find(_receive_asset->id) != _sell_asset->options.whitelist_markets.end():
```

If I remove the first order or make add ```bitshares = BitShares()``` above the second order, the second order goes through. Maybe this is an issue with pybitshares or something else?

UPDATE: 

If there is ```market1.bitshares.clear()``` before the second sell order, then the second sell order goes through. Using ```bitshares = BitShares(nobroadcast=True)``` also removes the crash.

**Comment by xeroc** [comment]
```
bitsharesapi.exceptions.UnhandledRPCError: Assert Exception: _sell_asset->options.whitelist_markets.find(_receive_asset->id) != _sell_asset->options.whitelist_markets.end():```

That error means that the issuer (cryptobridge) has disabled that market for trading. Please contact CryptoBridge for further assistance

**Comment by TuJuXorX** [comment]
@xeroc The trading of the first asset has been disabled on CryptoBridge, but not the second one. Neither order is going through using the code above. Somehow failure of the first order screws up the second order as well. If I create a new bitshares instance for the second order, then it goes through. Should it work like that?

**Comment by xeroc** [comment]
> @xeroc The trading of the first asset has been disabled on CryptoBridge, but not the second one. Neither order is going through using the code above. Somehow failure of the first order screws up the second order as well. If I create a new bitshares instance for the second order, then it goes through. Should it work like that?

Clearly not.

Can you use
``` from pprint import pprint

...

pprint(market1.sell(price=0.00003302, amount=10, account=account_name))

...

pprint(market2.sell(price=0.00001685, amount=10, account=account_name))

```

So that we can take a look at the actualy transactions?

**Comment by TuJuXorX** [comment]
@xeroc It seems that it is possible to print the result only if the order goes through. If the order doesn't go through, the code crashes like before and prints the same output as in my first comment. I had to use print instead of pprint, because I was getting "TypeError:` 'module' object is not callable" otherwise.

**Comment by bor0ka** [comment]
If I try to cancel an existing order then I'll get  exception:

`Traceback (most recent call last):
** IDLE Internal Exception: 
  File "/usr/local/lib/python3.5/dist-packages/bitsharesapi/bitsharesnoderpc.py", line 54, in rpcexec
    return self.rpc.rpcexec(self, payload)
  File "/usr/local/lib/python3.5/dist-packages/grapheneapi/graphenewsrpc.py", line 173, in rpcexec
    raise RPCError(ret['error']['message'])
grapheneapi.exceptions.RPCError: Assert Exception: maybe_found != nullptr: Unable to find Object

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<pyshell#5>", line 1, in <module>
    market.cancel('1.7.69503275',account='bor0bot')
  File "/usr/local/lib/python3.5/dist-packages/bitshares/market.py", line 530, in cancel
    return self.blockchain.cancel(orderNumber, account=account, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/bitshares/bitshares.py", line 1202, in cancel
    return self.finalizeOp(op, account["name"], "active", **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/bitshares/bitshares.py", line 293, in finalizeOp
    return self.txbuffer.broadcast()
  File "/usr/local/lib/python3.5/dist-packages/bitshares/transactionbuilder.py", line 387, in broadcast
    raise e
  File "/usr/local/lib/python3.5/dist-packages/bitshares/transactionbuilder.py", line 385, in broadcast
    ret, api="network_broadcast")
bitsharesapi.exceptions.UnhandledRPCError: Assert Exception: maybe_found != nullptr: Unable to find Object`

And after that does not work `market.sell(), market.buy()`.

**Comment by TuJuXorX** [comment]
@bor0ka While we wait @xeroc to fix the issue, you can use market.clear() after the error occurs, then market.sell() and market.buy() should keep working. No idea why cancelling of the order is failing though...

**Comment by bor0ka** [comment]
after market.clear() or bitshares.clear() still does not work :(
